### ISSUE TITLE
User can view a random cat picture.

### ISSUE THREAD

**Issue by Rachael-Kim** [rachaelkim831/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view random cat picture

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Cat picture will auto generate once random button is clicked

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/63431636/134235017-73a89c0d-94a8-4fdd-a1f7-d93ce86fe8ac.png)
![image](https://user-images.githubusercontent.com/63431636/134235072-70a987f7-8168-407d-9f40-f3400845cc0b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Write HTML and CSS to match wireframe design
- [x] Add dummy entries on homepage
- [x] Make sure random cat picture is generated when 'random' button is clicked
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
