### ISSUE TITLE
User can save a cat picture to their favorites list.

### ISSUE THREAD

**Issue by Rachael-Kim** [rachaelkim831/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save cat picture to their favorite list. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on Random button, new entry form pops up with URL autogenerated/ pre-filled. User will be able to edit title and notes. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create array or object in data js to store the entries. 
- [x] Complete HTML and CSS to match wire frame. 
- [x] Add Local Storage
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
